### PR TITLE
fix: vertical tabs and bottom border of boxed tabs

### PR DESCRIPTION
**Pull request by MaTTze**
a new try to fix the bottom border of boxed tabs. this time there is a bottom border over the whole length, just like in Bulma.
Additionaly I fixed vertical tabs and the positions.

### CODE REVIEW

**Comment by jtommy** [comment]
@MaTTze 
About boxed there are 2 issues:

image

Disabling multiline the tabs is not scrollable and break the page

image

Only for music tab (when active) there is the bottom border line

**Comment by MaTTze** [comment]
@jtommy I looked into it but I couldn't get it to work. It either is not scrollable or the active bottom-border is cut off. As far as I could track it the problem is the difference in structure (single `div.tabs` in oruga vs. `div.tabs>ul` in bulma)

**Comment by jtommy** [comment]
Probably we have to write it from scratch

**Comment by MaTTze** [comment]
Are you ok with changes to (the template in) oruga-ui?

**Comment by jtommy** [comment]
What changes? Oruga cannot change template for each CSS framework..

**Pull request closed without merging**
