### PR TITLE
fix: modal content covered by background

### LINKED ISSUE #78: Modal: Content is covered by background
### I gues the class `modal-content` was not set which gives the error

Screenshot

[View the docs.](https://oruga.io/components/Modal.html)
The problem only occurs in the context of the Bulma theme.

### PR DESCRIPTION
**Pull request by IlyaSemenov**
Fix #78

### CODE REVIEW

**Comment by jtommy** [comment]
@IlyaSemenov the problem is modal-card, following Bulma docs https://bulma.io/documentation/components/modal/#modal-card, it doesn't need that class

**Comment by IlyaSemenov** [comment]
@jtommy But the base Bulma modal needs it (quoting the link above):

> The modal structure is very simple:
> - modal: the main container
>     - modal-background: a transparent overlay that can act as a click target to close the modal
>     - modal-content: a horizontally and vertically centered container, with a maximum width of 640px, in which you can include any content
>     - modal-close: a simple cross located in the top right corner

 and `o-modal` is not supposed to be coupled with `modal-card`, is it?

**Comment by IlyaSemenov** [comment]
From what I gathered, modal-card can live happily inside modal-content (that's how buefy worked anyway).

**Comment by jtommy** [comment]
@IlyaSemenov thanks

**Pull request merged**
