### PR TITLE
Feat/bulma 1.0

### PR DESCRIPTION
**Pull request by messenjer**
Fix: https://github.com/oruga-ui/theme-bulma/issues/100

### CODE REVIEW

**Comment by jtommy** [comment]
@messenjer does It already completed?

**Comment by messenjer** [comment]
@jtommy, I fixed all the conflicts.

This branch works with bulma v1, but the following remains to be done:

- [ ] update the docs, with Dart Sass's new [@use and @forward keywords](https://sass-lang.com/documentation/at-rules/use/) instead of import. --> https://bulma.io/documentation/start/migrating-to-v1/ 
- [ ] convert the oruga/theme-bulma `sass variables` to `css variables`, ie: `$carousel-arrow-background <-- --oruga-carousel-arrow-background`
- [ ] remove the migrate variables --> `src/assets/scss/components/utils/_variables-to-migrate.scss`

Regards

Mathieu

**Comment by jtommy** [comment]
Are you going to work on theese points?

**Comment by messenjer** [comment]
@jtommy At the moment, I don't have much time again.

We're using oruga 0.7 for a project that's already in production, and for the moment there's no new development planned.

So it's not easy for me to find the time to work on it.

I'm just trying to keep things moving forward so that the day we develop new features, I can plan a migration to oruga 0.8 and bulma 1.0.

**Comment by lucraraujo** [comment]
Hi @messenjer and @jtommy . I'm entering a phase in a project where will take a relative long time to release a new version and I'm willing to help in this adaptation, but I'm a bit lost in how to develop the theme. Which commands show I use? Can I use Yarn or I need to use NPM.

I hope I can be helpful.

**Comment by jtommy** [comment]
You can use npm, free to review it and fix/improve it

**Comment by mlmoravek** [comment]
@messenjer I would like to bring this theme up to date.
Do you want to finish this bulma 1.x update yourself? Or should I clone your changes and make my own MR to finish it?

**Comment by messenjer** [comment]
> @messenjer I would like to bring this theme up to date with oruga changes. Do you want to finish this bulma 1.x update yourself? Or should I clone your changes and make my own MR to finish it?

Yes, you can. Unfortunately, I didn't work anymore on my previous project using oruga. I moved to another company.

**Comment by mlmoravek** [comment]
> Yes, you can. Unfortunately, I didn't work anymore on my previous project using oruga. I moved to another company.

Alright, thanks for your work. 

I hope you will have the chance to come back to Oruga with future projects. We are moving forward :)

**Pull request closed without merging**
